### ISSUE TITLE
The type of `iat` and `exp` should be checked.  

### ISSUE THREAD

**Issue by sallner** [gematik/app-gemRAS#6]
Hello, 

thanks for providing the testsuite for entity statements for the TI federation. 

We relied on this testsuite and got excepted, just to be reminded later, that the type of the `iat` an `exp` claim have not been integers correctly. It would be nice, if you could at least a type check and maybe a `iat < exp` into this testsuite. 

Looking at the TU there are actually some other statements with this behaviour.

Thanks for the work!

**Comment by RStaeber** [comment]
Release 
https://github.com/gematik/app-gemRAS/releases/tag/4.1.2
should fix this issue.
